/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_github_coderodde_util_FastBitCount */

#ifndef _Included_com_github_coderodde_util_FastBitCount
#define _Included_com_github_coderodde_util_FastBitCount
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_github_coderodde_util_FastBitCount
 * Method:    popcnt
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_github_coderodde_util_FastBitCount_popcnt
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
